### ISSUE TITLE
Recording Desktop screen to a file

### ISSUE THREAD

**Issue by winwisely99** [adrg/libvlc-go#23]
We need a way to record a video of the screen.

The use case is UAT testers, and VLC looks like a good one since it works cross platform.

Here is our issue if your curious:
https://github.com/winwisely99/dev/issues/31

SO first up - any API to set this up.
Manual way is documented here: https://www.makeuseof.com/tag/record-screen-using-vlc/

**Comment by adrg** [comment]
@winwisely99 Recording capabilities would be a very nice addition to the package. I will look into it when I get a bit of time. It would make sense to be able to record and save (or broadcast) video streams. The screen would be a special type of video stream.

I think VLC does this through a plugin but I need to check in order to be sure.

**Comment by adrg** [comment]
@winwisely99 I created a screen recording example:
https://github.com/adrg/libvlc-go/blob/master/v3/examples/gtk_screen_recorder.go

I added some GUI to the example using go-gtk for ease of use. However, you can extract only the recording part and integrate it in your application, which starts at line 170 in the example.

The libVLC [screen module](https://wiki.videolan.org/Documentation:Modules/screen) needs to be installed in order to have screen recording capabilities. On Debian based distributions, you can install the `vlc-plugin-access-extra` package.
```bash
sudo apt-get install vlc-plugin-access-extra
```
See https://github.com/adrg/libvlc-go/wiki for installation instructions for Windows.

**Comment by adrg** [comment]
Closing this issue as it has been addressed. Please reopen if there are any issues with the provided solution.
