### ISSUE TITLE
could not determine kind of name for C.libvlc_media_list_player_get_media_player

### ISSUE THREAD

**Issue by issueci** [adrg/libvlc-go#41]
https://github.com/adrg/libvlc-go/blob/cf9c068890dd9f0d7ed909d3e2eb889ac378246a/v3/list_player.go#L58

home/src/github.com/adrg/libvlc-go/v3/list_player.go:58:12: could not determine kind of name for C.libvlc_media_list_player_get_media_player

**Comment by adrg** [comment]
Hi @issueci. Could you provide more information about the issue? What version of libVLC do you have installed? I think you have a very old version of libVLC, probably some version of v2, lower than 2.2. The list player feature was first introduced in v2.2 of libVLC.

If that's the case, you must install a newer version of libVLC if you want to use the v3 package. Otherwise, you can use the v2 version of the package in legacy mode, as specified in the installation section of the README: https://github.com/adrg/libvlc-go#installation

**Comment by issueci** [comment]
Hi @adrg I'm using an arm based processor
<a href="https://ibb.co/MMFqVqr"><img src="https://i.ibb.co/4PhBTBz/2020-03-31-10-20-31-192-168-5-247-root.png" alt="2020-03-31-10-20-31-192-168-5-247-root" border="0"></a>

**Comment by adrg** [comment]
Did `go get` download the package for you, in spite of the error? That should be a build error. 
If so, try building with: `go build -tags legacy`.

Otherwise try:
```
go get -d github.com/adrg/libvlc-go/v2
go build -tags legacy
```

**Comment by issueci** [comment]
<a href="https://ibb.co/2sf4qXr"><img src="https://i.ibb.co/hZtzspN/2020-03-31-10-20-31-192-168-5-247-root.png" alt="2020-03-31-10-20-31-192-168-5-247-root" border="0"></a>

**Comment by adrg** [comment]
I'm not sure about that. That's an issue with the GTK bindings (https://github.com/gotk3/gotk3). Seems you have a very old version of GTK as well :). 

I see there is something specified in the README of the gotk3 project regarding this.
You could try:
```
go build -tags "gtk_deprecated legacy"
```
or
```
go build -tags "gtk_3_10 gtk_deprecated legacy"
```

Isn't there any possibility of getting newer versions of libVLC and GTK3 on the system you are building?

**Comment by issueci** [comment]
I will look for other solutions.
Thank you
