### ISSUE TITLE
create function to "LoadMediaFromBuffer"

### ISSUE THREAD

**Issue by frenos** [adrg/libvlc-go#64]
I would like to propose a new feature:
Create a function to load new media from a (go) []byte.

Background:
I'm creating a stream processor that gets a lot of short videos as bytes from a message queue, reads the metadata and writes that to another queue. libvlc-go is working great for this except one thing that is currently my bottleneck: I have to write all incoming blobs to a temporary file, process them and delete the temporary file. This causes a lot of unnecessary load on the disk.

**Comment by adrg** [comment]
Hi @frenos. Thank you for your interest in the library. This seems like a pretty useful feature.

 libVLC does not make it easy to load media from byte streams. I need to implement the [libvlc_media_new_callbacks](https://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc__media.html#ga591c3cbe56444f1949165b2b9b75d8e2) binding in order to support this and probably an abstraction over `io.ReadSeeker` to satisfy the callbacks libVLC requires, so it is not trivial. 
However, this seems like a common use case, so it's definitely something I want to support. I'll start working on it when I get some free time. I'll let you know when this is done (most likely some time next week).

**Comment by adrg** [comment]
Hi @frenos. I added `vlc.NewMediaFromReadSeeker` and `Player.LoadMediaFromReadSeeker` in version [3.0.9](https://github.com/adrg/libvlc-go/releases/tag/v3.0.9).

You can use a [bytes.Reader](https://pkg.go.dev/bytes#Reader) instance to create a `ReadSeeker` from your byte data.

```go
var videoBytes []byte
media, err := vlc.NewMediaFromReadSeeker(bytes.NewReader(videoBytes))
player.SetMedia(media)
```
or

```go
var videoBytes []byte
media, err := player.LoadMediaFromReadSeeker(bytes.NewReader(videoBytes))
```
