### ISSUE TITLE
Windows “static” dll build

### ISSUE THREAD

**Issue by asimpson** [adrg/libvlc-go#85]
My program compiled fine but when it's run on a different Windows machine I get an error that libvlc.dll could not be found. 

Is it possible to build the binary such that users of the program don't need to have libvlc.dll on their machine? Basically, is it possible to do a static build on Windows like it is on Linux?

**Comment by asimpson** [comment]
Additional notes: this is the same problem as outlined in #61. However it's not clear to me if the solution ended up being a "self-contained" binary from Go or having to require the libvlc.dll on the machine with the binary.

**Comment by adrg** [comment]
Hi @asimpson. Thank you for your interest in the library.

It should be possible to statically link libVLC, although I don't think it's that easy. I've never attempted it. I think dynamic linking is recommended by VideoLAN as well on their wiki, if I remember correctly.

Is distributing `libvlc.dll` along your binary not possible for you? That's all that's needed really. If `libvlc.dll` is in the same directory as your binary, it should work.


> Is it possible to build the binary such that users of the program don't need to have libvlc.dll on their machine? Basically, is it possible to do a static build on Windows like it is on Linux?

It's not static linking on Linux either.

> Additional notes: this is the same problem as outlined in #61. However it's not clear to me if the solution ended up being a "self-contained" binary from Go or having to require the libvlc.dll on the machine with the binary.

That issue was referring to the development phase, so yes, the libVLC SDK (headers + DLLs) was present on the machine.

**Comment by adrg** [comment]
Closing this issue as it has been addressed.
